### ISSUE TITLE
Keep getting Requiriring unkown module.

### ISSUE THREAD

**Issue by msmakhlouf** [NishanthShankar/react-native-android-statusbar#3]
Following the steps in Readme, I only get this error!

**Comment by richarddewit** [comment]
@msmakhlouf - did you restart the Android packager afterwards? (`react-native run-android`)

**Comment by kirillplatonov** [comment]
@richarddewit Hi. I did. But I still receive this error =(

**Comment by pradel** [comment]
I have same error too with react-native 0.14

**Comment by NishanthShankar** [comment]
sorry guys, I am unable to reproduce this error. Could you please ensure that you've done all five steps in the readme
- npm install
- update settings.gradle
- update build.gradle
- update MainActivity.java 
- run react-native run-android

**Comment by pradel** [comment]
I reboot my computer and it's working now (weird) thanks

**Comment by chrisnager-iex** [comment]
Ha, rebooting my computer worked for me, too. So strange.

**Comment by arshsingh** [comment]
`react-native run-android` just builds the apk, you have to restart the packager (`react-native start`)

Prior to react-native 0.16, `react-native run-android` also started the packager in a new shell, so when you do `react-native run-android` again, it doesnt start the packager again because it's already running.
Which is why the error went away for you guys when you restarted your computer.

This issue should be closed now @NishanthShankar
